server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classicmodels
    password: Sunil
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
  application:
    name: PRODUCT-SERVICE